### ISSUE TITLE
Reporting a crash in protoss 03 (cleaning up xel naga temple mission)

### ISSUE THREAD

**Issue by nad53** [BoneHorror/UEDAIProject#1]
Hey sir. I was actually playing your MOD with way harder Brood War missions and just got a crash when trying to take the lower-mid expansion in protoss03 mission... Once I was going to place the nexus it crashed ...

I'm sending you the file I was notified to see but I can't really understand it... I really hope you read this message and try to fix it (if possible) ... I already completed the terran campaign and it was a really pain in the ass realizing how to beat the mission 8 (even though I'm not a super newbie player since I used to play against professionals and I have some sort of speed and I don't try to pretend to be vain by the way)...

One additional question is: Could you actually develop the very first 3 campaigns from SC1 vanilla ? Seeing how well you improved the difficulty it would be so outstanding to play your harder version in all that 30 missions ... 

Regards buddy and thank you for all your amazing work in this project !

[Crash.txt](https://github.com/BoneHorror/UEDAIProject/files/2971963/Crash.txt)

P.D: I tried to upload the file.dmp but seems to not working so I will upload it do onedrive for you >> 

https://1drv.ms/u/s!AtKS8lBxejvUdVRqZ8C0hnStMMM
https://1drv.ms/t/s!AtKS8lBxejvUdJMNlKIBYfhbCTU

**Comment by nad53** [comment]
A new crash ... Just took recently the third expansion in the lower right part of the map... then moving some units in the bottom of map attacking some ultralisk + hidralisks then crashed once again suddendly ... Here is the .DMP file >> https://1drv.ms/u/s!AtKS8lBxejvUdiEabkhfdJ6agAA

I hope you can fix it buddy, great job in the missions once again.

**Comment by BoneHorror** [comment]
Sorry for not noticing the issue, I don't really check github all that often. I am working on finishing episode 4 as well as plan on working on episodes 1, 2 and 3, Enslavers and Enslavers II from the Starcraft campaign. I believe your exe was made outdated by a Blizzard patch (they break mods every now and then) and seeing when you reported the issue, that's likely the case. The newest version should work fine.
